# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shhuang <dsheng1993@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/14 19:24:23 by shhuang           #+#    #+#              #
#    Updated: 2023/08/14 19:24:23 by shhuang          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@clear
	c++ file.cpp -std=c++98 -Wall -Wextra -Werror -o phonebook

fclean: 
	@echo "cleaning"
	rm -f phonebook